// This file is now deprecated. Use the database-driven resource service instead.
// resourcesData has been migrated to data/resources.json and the database.

export const resourcesData = [
  {
    id: "1",
    title: "Introduction to Computer Science - Harvard's CS50",
    description: "Comprehensive introduction to computer science and programming",
    url: "https://www.youtube.com/watch?v=8mAITcNt710",
    platform: "youtube",
    type: "video",
    category: "computer-science",
    tags: ["programming", "computer science", "introduction"],
    duration: "2h 15m",
    rating: 4.9,
    views: 12500000,
    courseIds: ["intro-to-cs", "fundamentals-computing"],
  },
  {
    id: "2",
    title: "Learn Python - Full Course for Beginners",
    description: "Complete Python tutorial covering all the basics",
    url: "https://www.youtube.com/watch?v=rfscVS0vtbw",
    platform: "youtube",
    type: "video",
    category: "programming",
    tags: ["python", "programming", "beginners"],
    duration: "4h 27m",
    rating: 4.8,
    views: 28300000,
    courseIds: ["intro-to-python", "intro-to-cs"],
  },
  {
    id: "3",
    title: "Linear Algebra - Khan Academy",
    description: "Full course on linear algebra concepts",
    url: "https://www.khanacademy.org/math/linear-algebra",
    platform: "khan-academy",
    type: "course",
    category: "mathematics",
    tags: ["linear algebra", "mathematics", "vectors"],
    duration: "15h",
    rating: 4.7,
    lessons: 45,
    courseIds: ["linear-algebra", "math-for-cs"],
  },
  {
    id: "4",
    title: "Data Structures and Algorithms - MIT OpenCourseWare",
    description: "Advanced course on data structures and algorithm design",
    url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/",
    platform: "mit-ocw",
    type: "course",
    category: "computer-science",
    tags: ["algorithms", "data structures", "advanced"],
    duration: "20h",
    rating: 4.9,
    lessons: 24,
    courseIds: ["data-structures", "data-structures-2"],
  },
  {
    id: "5",
    title: "Database Design - Stanford Online",
    description: "Comprehensive database design and SQL course",
    url: "https://www.edx.org/course/databases-5-sql",
    platform: "edx",
    type: "course",
    category: "computer-science",
    tags: ["databases", "sql", "design"],
    duration: "12h",
    rating: 4.6,
    lessons: 18,
    courseIds: ["database-systems", "database-systems-2"],
  },
  // Electrical Engineering Resources
  {
    id: "6",
    title: "Circuit Analysis - Khan Academy",
    description: "Fundamental circuit analysis techniques",
    url: "https://www.khanacademy.org/science/electrical-engineering",
    platform: "khan-academy",
    type: "course",
    category: "electrical-engineering",
    tags: ["circuits", "analysis", "beginners"],
    duration: "10h",
    rating: 4.7,
    lessons: 30,
    courseIds: ["circuit-analysis", "basic-electrical-circuits"],
  },
  {
    id: "7",
    title: "Electronics Fundamentals - MIT OpenCourseWare",
    description: "Introduction to electronic components and circuits",
    url: "https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/",
    platform: "mit-ocw",
    type: "course",
    category: "electrical-engineering",
    tags: ["electronics", "components", "intermediate"],
    duration: "15h",
    rating: 4.8,
    lessons: 26,
    courseIds: ["electronics-1", "electronics-2"],
  },
  {
    id: "8",
    title: "Digital Electronics - Coursera",
    description: "Digital logic design and implementation",
    url: "https://www.coursera.org/learn/digital-electronics",
    platform: "coursera",
    type: "course",
    category: "electrical-engineering",
    tags: ["digital", "logic", "design"],
    duration: "8h",
    rating: 4.5,
    lessons: 12,
    courseIds: ["digital-logic", "digital-systems"],
  },
  {
    id: "9",
    title: "Power Systems Analysis - edX",
    description: "Analysis and design of electrical power systems",
    url: "https://www.edx.org/course/power-systems-analysis",
    platform: "edx",
    type: "course",
    category: "electrical-engineering",
    tags: ["power", "systems", "advanced"],
    duration: "14h",
    rating: 4.6,
    lessons: 20,
    courseIds: ["power-systems", "power-systems-2"],
  },
  // Business Administration Resources
  {
    id: "10",
    title: "Introduction to Business - Harvard Business School",
    description: "Fundamental business concepts and principles",
    url: "https://www.hbs.edu/online-learning/",
    platform: "hbs-online",
    type: "course",
    category: "business-admin",
    tags: ["business", "introduction", "fundamentals"],
    duration: "6h",
    rating: 4.8,
    lessons: 12,
    courseIds: ["intro-business", "principles-management"],
  },
  {
    id: "11",
    title: "Financial Accounting - Coursera",
    description: "Complete course on financial accounting principles",
    url: "https://www.coursera.org/learn/financial-accounting",
    platform: "coursera",
    type: "course",
    category: "business-admin",
    tags: ["accounting", "finance", "intermediate"],
    duration: "10h",
    rating: 4.7,
    lessons: 16,
    courseIds: ["financial-accounting", "principles-accounting"],
  },
  {
    id: "12",
    title: "Marketing Principles - Stanford Online",
    description: "Core marketing concepts and strategies",
    url: "https://online.stanford.edu/courses/sohs-ystanford-0001-marketing-principles",
    platform: "stanford-online",
    type: "course",
    category: "business-admin",
    tags: ["marketing", "strategy", "principles"],
    duration: "8h",
    rating: 4.6,
    lessons: 14,
    courseIds: ["marketing-principles", "marketing-management"],
  },
  {
    id: "13",
    title: "Strategic Management - MIT Sloan",
    description: "Advanced strategic management and planning",
    url: "https://mitsloan.mit.edu/executive-education/online-programs",
    platform: "mit-sloan",
    type: "course",
    category: "business-admin",
    tags: ["strategy", "management", "advanced"],
    duration: "12h",
    rating: 4.9,
    lessons: 18,
    courseIds: ["strategic-management", "business-analysis"],
  },
  // Nursing Resources
  {
    id: "14",
    title: "Anatomy and Physiology - Khan Academy",
    description: "Comprehensive human anatomy and physiology course",
    url: "https://www.khanacademy.org/science/health-and-medicine",
    platform: "khan-academy",
    type: "course",
    category: "nursing",
    tags: ["anatomy", "physiology", "health"],
    duration: "20h",
    rating: 4.8,
    lessons: 40,
    courseIds: ["anatomy-physiology-1", "anatomy-physiology-2"],
  },
  {
    id: "15",
    title: "Nursing Fundamentals - Coursera",
    description: "Basic nursing skills and patient care",
    url: "https://www.coursera.org/learn/nursing-fundamentals",
    platform: "coursera",
    type: "course",
    category: "nursing",
    tags: ["nursing", "fundamentals", "patient-care"],
    duration: "8h",
    rating: 4.6,
    lessons: 12,
    courseIds: ["nursing-fundamentals", "fundamentals-nursing"],
  },
  {
    id: "16",
    title: "Health Assessment - edX",
    description: "Comprehensive health assessment techniques",
    url: "https://www.edx.org/course/health-assessment",
    platform: "edx",
    type: "course",
    category: "nursing",
    tags: ["assessment", "health", "clinical"],
    duration: "10h",
    rating: 4.7,
    lessons: 16,
    courseIds: ["health-assessment"],
  },
  {
    id: "17",
    title: "Pharmacology for Nurses - Stanford Online",
    description: "Essential pharmacology knowledge for nursing practice",
    url: "https://online.stanford.edu/courses/sohs-ystanford-0002-pharmacology-nurses",
    platform: "stanford-online",
    type: "course",
    category: "nursing",
    tags: ["pharmacology", "medications", "nursing"],
    duration: "12h",
    rating: 4.8,
    lessons: 20,
    courseIds: ["pharmacology", "pharmacology-1"],
  },
  // Additional Computer Science Resources
  {
    id: "18",
    title: "Operating Systems - Berkeley CS",
    description: "Advanced operating systems concepts and design",
    url: "https://cs162.eecs.berkeley.edu/",
    platform: "berkeley-cs",
    type: "course",
    category: "computer-science",
    tags: ["operating systems", "advanced", "systems"],
    duration: "16h",
    rating: 4.8,
    lessons: 22,
    courseIds: ["operating-systems", "os-advanced"],
  },
  {
    id: "19",
    title: "Artificial Intelligence - Stanford CS",
    description: "Introduction to AI and machine learning",
    url: "https://cs221.stanford.edu/",
    platform: "stanford-cs",
    type: "course",
    category: "computer-science",
    tags: ["ai", "machine learning", "advanced"],
    duration: "18h",
    rating: 4.9,
    lessons: 24,
    courseIds: ["artificial-intelligence", "machine-learning"],
  },
  {
    id: "20",
    title: "Web Development - Full Stack Open",
    description: "Modern web development with React and Node.js",
    url: "https://fullstackopen.com/",
    platform: "fullstack-open",
    type: "course",
    category: "computer-science",
    tags: ["web development", "react", "node.js"],
    duration: "14h",
    rating: 4.7,
    lessons: 20,
    courseIds: ["web-development", "advanced-web"],
  }
]; 